# .pre-commit-config.yaml
repos:
  # Pre-commit hooks for general YAML and JSON linting
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: trailing-whitespace
      - id: end-of-file-fixer

  # Terraform hooks for linting and formatting Terraform code
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.95.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_docs
      - id: checkov

  # Dockerfile linting
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint

  # Markdown linting
  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.13.0
    hooks:
      - id: markdownlint

  - repo: local
    hooks:
      # PHP Lint (syntax checking)
      - id: php-lint
        name: PHP linting (php -l)
        entry: bash -c 'find . -name "*.php" -exec php -l {} \;'
        language: system
        types: [php]

      # PHP CodeSniffer (code style checking)
      - id: phpcs
        name: PHP CodeSniffer
        entry: ./php/vendor/bin/phpcs --standard=PSR12
        language: system
        types: [php]

      # PHP-CS-Fixer (optional: for fixing code style issues)
      - id: php-cs-fixer
        name: PHP-CS-Fixer
        entry: ./php/vendor/bin/php-cs-fixer fix --diff
        language: system
        types: [php]
