apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "php.fullname" . }}-servicemonitor
  labels:
    {{- include "php.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "php.selectorLabels" . | nindent 4 }}
  endpoints:
  - port: "{{ .Values.service.port }}"
    path: /metrics
    interval: 30s
