apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-php-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/<YOUR_USERNAME>/<YOUR_REPO>.git'
    path: helm
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true