apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-php-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/jeffwhite06/modern-cicd.git'
    path: helm
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true